spring:
  application:
    name: ReactiveREST

  data:
    mongodb:
      host: localhost
      port: 27017
      database: ReactiveREST

  redis:
    database: 12
    host: localhost
    port: 6379

server:
  port: 8081

